### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by paskalito**
not fully finished yet im tired..

### CODE REVIEW

**Comment by einmalfel** [comment]
Vielen Dank, @paskalito !

I have few remarks though. Is it possible to:
 * write one-letter hour & minute abbreviations in Deutsch? Like "h" and "m" in English? Episode list layout is designed for short duration strings, like "1h5m". Longer ones will not fit into it.
 * make refresh_mode strings shorter? Maybe it's possible to remove "hinzufügen" word from them? "Hinzuzufügender" will be shown in refresh mode spinner title anyway. Otherwise options in spinner will contain line wraps, which doesn't look neatly IMO
 * express preferences_storage_location_title and preferences_pause_on_disconnect_title a little shorter? Ideally they should fit in one line in preferences screen

I've made screenshots to illustrate what I'm talking about:

**Comment by paskalito** [comment]
hey, you're welcome and thank you for programming the whole app ;)

it's cool to see the effect of my work in screenshots :D

- I changed Stdn. to h which is actually more common in german as well. but i let min the way it was. the problem with m is in german that means meter. But if you really think that still uses to much space you can change it to m as well it would be "wrong" but people will still understand  - and i think many won't even notice. - or i think something like 2h12  without anything in addition might even be better...
- point 2 with removing "Hinzuzufügender" works perfect. one could even remove "Episoden" as well.
- storage location > i really did not manage to make it shorter only a little tiny bit  // pause_on_disconnect > is not particularery nice in the new version but it works. ^^ // donwload_ac is now a lot shorter an clearer at the same time YEY :)

(if you cannot see any new pull by now or somethin tell me i have no experience in doing that by now)

**Comment by einmalfel** [comment]
@paskalito "m" stands for both meter and minute in Russian and English too, and it's still looks clear in this context.
Strings like "2h22min" will not fit into layout. I think it's better to left it "h" and "m" if it's still understandable for Germans.

I've tested the translation and it looks quite good (except for storage location preference, but it's too long in all languages, I'll fix this later).
I'm merging your changes into master, thanks for contribution :+1:

**Comment by paskalito** [comment]
@einmalfel  i just checked wikipedia and it really seems m is only for meter an minutes only know min as shortener, BUT noone will care..
thanks for letting me help and the nice commnication. and of course tahnks a lot for developing this great app under gpl :D 
Im really excited about the next update :D 
and of course you can, im not always on the line / computers - but i will get the mail from github sooner or later ;)
all the best

**Pull request merged**
